[tool.isort]
profile = "black"
sections = "STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
order_by_type = true
force_sort_within_sections = true
line_length = 88
case_sensitive = false

[tool.pylint.main]
load-plugins = []
jobs = 4 

[tool.pylint.messages_control]
disable = [
    "C0114",
    "C0115",
    "C0116",
]

[tool.pylint.format]
max-line-length = 88
indent-string = "    "

[tool.pylint.basic]
variable-rgx = "^[a-z_][a-z0-9_]{2,30}$"
function-rgx = "^[a-z_][a-z0-9_]{2,30}$"
argument-rgx = "^[a-z_][a-z0-9_]{2,30}$"
attr-rgx = "^[a-z_][a-z0-9_]{2,30}$"
class-rgx = "^[A-Z_][a-zA-Z0-9]+$"