name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      # Étape 3 : Mise en cache des dépendances
      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Étape 4 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 5 : Vérification avec Black
      - name: Check code formatting with Black
        run: |
          .venv/bin/python -m black --check src

      # Étape 6 : Vérification de l'ordre des imports avec isort
      - name: Check import sorting with isort
        run: |
          .venv/bin/python -m isort --check-only src

      # Étape 7 : Analyse de linting avec Pylint
      - name: Lint code with pylint
        run: |
          .venv/bin/python -m pylint src/
